font_family GeistMono Nerd Font Mono
font_size 14

color1   #ff0000
color9   #ff0000
disable_ligatures no
enable_audio_bell no

shell                  zsh
shell_integration disabled


cursor_shape beam
cursor_beam_thickness 1.5

url_style curly


remember_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 20
cursor_blink_interval 0


background_opacity            0.85
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
confirm_os_window_close       0


sync_to_monitor no

#colors

background            #222221
foreground            #e4e4e4
cursor                #16aec9
selection_background  #dedede
color0                #212121
color8                #424242
color1                #b7141e
color9                #e83a3f
color2                #457b23
color10               #7aba39
color3                #f5971d
color11               #fee92e
color4                #134eb2
color12               #53a4f3
color5                #550087
color13               #a94dbb
color6                #0e707c
color14               #26bad1
color7                #eeeeee
color15               #d8d8d8
cursor                #ff0000
cursor_text_color     #ef4444
selection_foreground #222221
